### ISSUE TITLE
[HIGH] Ro Calculator

### ISSUE THREAD

**Issue by NicolasMorando** [maks500/ecm-FrontendServer#53]
Habría que agregar una "solapa" que contenga la siguiente hoja de cálculo (implementada de la manera más conveniente):

[Calculadora Ro.xlsx](https://github.com/maks500/ecm-FrontendServer/files/4842837/Calculadora.Ro.xlsx)

La idea es que el usuario sólo pueda ingresar números en las celdas que figuran en blanco. Los valores por default sean cero.

Esta hoja de cálculo debería ser independiente de la elección de modelos, por ejemplo, podría accederse como en la siguiente imagen:

![Ro Calculator](https://user-images.githubusercontent.com/22283938/85951794-d66e8e00-b93b-11ea-82b3-0a7abd050045.png)

**Comment by dgutson** [comment]
@NicolasMorando el R0 no toma parámetros que dependen del modelo?

**Comment by NicolasMorando** [comment]
@dgutson En parte sí, el calculador que estaríamos ofreciendo sería para un modelo "10G" donde se pueden desglosar los contactos según tipo, que sería el modelo más amplio que podemos ofrecer. Pero el cálculo que se hace no asume nada sobre los compartimentos (vale para SIR, SEIR, etc). Digo "independiente" porque a Daniel R le pareció mejor que fuera una funcionalidad separada de los "modelos" con la predicción de curvas, etc. Para el cálculo del Ro uno necesita menos información, sólo el p, gama, número de individuos y número de contactos por grupo. Pero no es necesario saber el sigma o el número inicial de infectados (porque el concepto de Ro por definición asume una población totalmente vulnerable con 1 infectado inicial).
